In [26]:
(data_frame <- data.frame(a=c(1), b=1))

a b
1 1 1

In [27]:
(b=1)

[1] 1

In [28]:
class(b)

[1] "numeric"

In [29]:
mode(b)

[1] "numeric"

In [30]:
typeof(b)

[1] "double"

In [31]:
(a = c(1,2,"3"))

[1] "1" "2" "3"

In [32]:
(listVar <- list(a=c(1,2,"3"), b=c(1,2,3)))

$a
[1] "1" "2" "3"

$b
[1] 1 2 3

In [33]:
(data_frame <- data.frame(a=c(1,2,"3"), b=c(1,2,3)))

a b
1 1 1
2 2 2
3 3 3

In [34]:
(nextMatrix <- as.matrix(data_frame))

a b
[1,] 1 1
[2,] 2 2
[3,] 3 3

In [35]:
(data_frame$b)

[1] 1 2 3

In [36]:
(listVar$b)

[1] 1 2 3

In [37]:
(class(nextMatrix[,1]))

[1] "character"

In [38]:
(class(nextMatrix[,2]));

[1] "character"

In [39]:
as.matrix(data_frame)

a b
[1,] 1 1
[2,] 2 2
[3,] 3 3

In [40]:
nextMatrix

a b
[1,] 1 1
[2,] 2 2
[3,] 3 3

In [41]:
?matrix

In [42]:
(A <- matrix (1:20,4,5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [43]:
A[2,3]

[1] 10

In [44]:
(B <- matrix(1:20, 4, 5, byrow = T))

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

In [45]:
(r1 <- c("I", "am", "in"))

[1] "I"  "am" "in"

In [46]:
?rbind

In [47]:
(r2 <- c(1,2,3)) 

[1] 1 2 3

In [48]:
(r3 <- rbind(r1,r2))

[,1] [,2] [,3]
r1 I    am   in  
r2 1    2    3

In [49]:
(r4 <- cbind(r1,r2))

r1 r2
[1,] I  1 
[2,] am 2 
[3,] in 3

<h2 style='color:red'> Question1 begin </h2>


In [50]:
(a<-3);

[1] 3

In [51]:
class(a)

[1] "numeric"

In [52]:
class(a1 <- 1.3)

[1] "numeric"

In [53]:
Charlie <- 1:5

In [54]:
class(Charlie)

[1] "integer"

In [55]:
(Charlie1 <- 1.1:5.1)

[1] 1.1 2.1 3.1 4.1 5.1

In [56]:
class(Charlie1)

[1] "numeric"

<h2 style='color:red'> Question1 end </h2>

In [57]:
is.object(Charlie)

[1] FALSE

In [58]:
is.object(data_frame)

[1] TRUE

In [59]:
is.object(Charlie1)

[1] FALSE

In [60]:
is.object(listVar)

[1] FALSE

In [61]:
?is.object

In [62]:
is.object(as.complex(1:3))

[1] FALSE

<h2 style='color:purple'> Page 74 </h2>
